apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: default
spec:
  {}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: tcp-echo
spec:
  selector:
    matchLabels:
      app: tcp-echo
  action: ALLOW
  rules:
  - to:
    - operation:
        ports:
        - '9000'
        - '9001'
---