apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - hosts:
    - edition.cnn.com
    port:
      name: http
      protocol: HTTP
      number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cnn
spec:
  hosts:
  - edition.cnn.com
  gateways:
  - mesh
  - egressgateway
  http:
  - match:
    - gateways:
      - mesh
      port: 80
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: cnn
  - match:
    - gateways:
      - egressgateway
      port: 80
    route:
    - destination:
        host: edition.cnn.com
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: cnn
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cnn
spec:
  hosts:
  - edition.cnn.com
  ports:
  - name: http
    protocol: HTTP
    number: 80
  - name: https
    protocol: HTTPS
    number: 443
  resolution: DNS
  location: MESH_EXTERNAL
---