apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny
spec:
  selector:
    matchLabels:
      app: httpbin
  action: DENY
  rules:
  - to:
    - operation:
        methods:
        - GET
    when:
    - key: request.headers[x-token]
      notValues:
      - admin
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow
spec:
  selector:
    matchLabels:
      app: httpbin
  action: ALLOW
  rules:
  - to:
    - operation:
        paths:
        - /ip
---