apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ingressgateway
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: DENY
  rules:
  - from:
    - source:
        ipBlocks:
        - '1.2.3.4'
        - '5.6.7.0/24'
        - '192.168.64.1'
---
